### ISSUE TITLE
Release a new haxelib version before moving to Pixi 5?

### ISSUE THREAD

**Issue by alamboley** [pixijs/pixi-haxe#166]
Hey @notboring, since you merged your fork inside this repo and made it Haxe 4 ready, it would be nice to release a new Haxelib version for Pixi.v4.8.8 before moving to V5. What do you think?

Thanks for your hard work!

**Comment by notboring** [comment]
Yes, that's making a lot of sense. I have been wondering how to properly do this since I don't have the password required to upload to the current pixijs haxelib repository.

The options that I see right now are:

- checking if AdiReddy provided eg @GoodBoyDigital with the password
- asking the haxe team if they might be a able to provide me with access by resetting the password or similar
- starting a new repository like it has been done for the haxe 4 version of nape

Let's see if Mat maybe got it. If not, I gonna ask someone from the Haxe Foundation.

**Comment by alamboley** [comment]
Oh yeah, I see the problem. I thought Haxelib was just looking for an update to the haxelib.json file for providing a new release. Didn't know the main Contributor has to do it manually.

I doubt that Mat got it, since he isn't at all in the Haxe ecosystem afaik. The best thing would be haxe team add you as a contributor. There may be several people like https://lib.haxe.org/p/openfl-js-extern. So we won't have a repository reset or moving it elsewhere.

**Comment by notboring** [comment]
Been asking for that on Haxe discord and Gamma11 mentioned that another project of Adi (haxe checkstyles) has been handled the way you described. Still didn't figure out who to contact for that, though. If I don't get any hints on discord today I'll open a ticket on the haxelib github repo.

Update: I created a pixijs specific email adress along with a pixijs specific haxelib account. Gamma11 will forward the account data to simn. Hopefully I get added then. If everything works out, I will provide @GoodBoyDigital with the access data for both accounts so we are safe in future.

Simn, to allow you to confirm my identity: The account is named 'pixijs' and has a tuta.io address.

**Comment by notboring** [comment]
The pixijs-Account has been added as haxelib repo owner and I updated the library: https://lib.haxe.org/p/pixijs/

Thanks a lot to Gama11 & Simn for their help!

@GoodBoyDigital What's the best way to send you the access data for the haxelib account?

**Comment by alamboley** [comment]
Awesome! Would be nice to upload the haxelib.json file on the github too ;)
